version: "3"

services:
  app:
    build: .
    command: npm run start

    ports:
      - "3000:3000"
    environment:      
      - DB_NAME=gria
      - DB_HOST=postgres
    volumes:
      - ".:/usr/app"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flight-manager
